/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/views/About.vue')['default']
    Blog: typeof import('./src/views/Blog.vue')['default']
    Contact: typeof import('./src/views/Contact.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/views/Main.vue')['default']
  }
}
